version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: interview-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interview-network

  identity-provider:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: interview-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
    ports:
      - "8180:8080"
    depends_on:
      - postgres-db
    networks:
      - interview-network

  zipkin:
    image: openzipkin/zipkin
    container_name: interview-zipkin
    ports:
      - "9411:9411"
    networks:
      - interview-network

volumes:
  postgres_data:
    driver: local

networks:
  interview-network:
    driver: bridge