version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: interview-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interview-network
    deploy:
      resources:
        limits:
          memory: 1G

  identity-provider:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: interview-keycloak
    restart: always
    command: start --optimized --http-enabled=true
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME_URL}
      KC_PROXY: edge

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - interview-network

  zipkin:
    image: openzipkin/zipkin:3
    container_name: interview-zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - interview-network

volumes:
  postgres_data:
    driver: local

networks:
  interview-network:
    driver: bridge